eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

server:
  port: 99

spring:
  application:
    name: zuul-server

#zuul:
#  routes:
#    service-product: /product/**
#    service-user: /user/**
#    service-order: /order/**
#  # ����service-*�ķ�ʽ����
#  # ignored-patterns: /service-*/**
#  # �����������񣬲������ṩ�ӿ�
#  #ignored-services: service-order


